name: Bug Report
description: Report a bug
labels: ["bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before you start
        > Please **make sure you are on the latest version.**
        Please fill out the sections below to help everyone identify and fix the bug
        
  - type: textarea
    id: expected
    attributes:
      label: Description
      description: Describe the issue
    validations:
      required: true
  
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Which exact steps can a developer take to reproduce the issue?
        The more detail you provide, the easier it will be to narrow down and fix the bug.
        Please provide your tasks and/or queries in text format, rather than as screenshots.
      placeholder: |
        Here's an example of the level of detail required to reliably and efficiently reproduce any bugs.
        1. Go to the '...' page.
        2. Click on the '...' button.
        3. Scroll down to '...'.
        4. Observe the error.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What was the expected result?
      placeholder: I expected this to happen

  - type: textarea
    id: screenshots
    attributes:
      label: Put here any screenshots or videos (optional)

  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: 'Acknowledgements'
      description: 'Please confirm the following:'
      options:
        - label: 'My issue title is concise, descriptive.'
          required: true
        - label: "I searched the existing issues to ensure this bug hasn't been reported."
          required: true
        - label: 'I am using the latest version of repo.'
          required: true
        - label: 'I have provided enough information for the maintainers to reproduce and diagnose the issue.'
          required: true
          
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! We will get back to you as soon as possible.
